"""Aggregate the experiment runs into the paper's canonical row set, tables, and macros.

Reads every outputs/runs/*/results.csv (schemas differ across runs), normalizes legacy
column names, keeps successfully scored rows, dedupes by output stem (latest run wins),
and emits:
  data/canonical_rows.csv   traceable row set (+run_id)
  tables/main_results.tex   Table 1 body
  tables/setup_models.tex   model/endpoint/cost table body
  tables/numbers.tex        \\newcommand macros for every number quoted in prose
"""

import sys

import pandas as pd
import yaml

from config import (
    CANONICAL_RUN_PREFIXES,
    CONTROL_NAMES,
    DATA_DIR,
    METRIC_COLS,
    MODEL_CONFIGS_DIR,
    MODEL_NAMES,
    PROCEDURE_NAMES,
    RUNS_DIR,
    TABLES_DIR,
    tex_escape,
)


def load_runs() -> pd.DataFrame:
    frames = []
    for csv in sorted(RUNS_DIR.glob("*/results.csv")):
        run_id = csv.parent.name
        if CANONICAL_RUN_PREFIXES is not None and not any(
            run_id.startswith(p) for p in CANONICAL_RUN_PREFIXES
        ):
            continue
        df = pd.read_csv(csv)
        df["run_id"] = run_id
        frames.append(df)
    if not frames:
        sys.exit(f"No results.csv found under {RUNS_DIR}")
    return pd.concat(frames, ignore_index=True, sort=False)


def normalize(df: pd.DataFrame) -> pd.DataFrame:
    # Early facelift runs predate the target/offtarget naming; for those runs the
    # lower face IS the target region and the upper face the keep zone.
    df["legacy_regions"] = False
    if "change_lower_face" in df.columns:
        legacy = df["change_target"].isna() & df["change_lower_face"].notna()
        df.loc[legacy, "change_target"] = df.loc[legacy, "change_lower_face"]
        df.loc[legacy, "change_offtarget"] = df.loc[legacy, "change_upper_face"]
        df.loc[legacy, "legacy_regions"] = True
    df["procedure"] = df["procedure"].replace({"facelift": "deep_plane_facelift"})
    return df


def dedupe(df: pd.DataFrame) -> pd.DataFrame:
    # Per stem keep the row with the most populated metrics; break ties by latest run
    # (some later runs replayed stems in an environment missing the eval extras, so
    # plain latest-wins would discard scored rows).
    df = df.assign(_n_metrics=df[METRIC_COLS].notna().sum(axis=1))
    df = df.sort_values(["_n_metrics", "run_id"])
    return df.drop_duplicates("stem", keep="last").drop(columns="_n_metrics")


def fmt(x, nd=3):
    return "--" if pd.isna(x) else f"{x:.{nd}f}"


def write_main_results(df: pd.DataFrame) -> None:
    rows = []
    grouped = df.groupby(["procedure", "model", "control"], sort=True)
    for (proc, model, control), g in grouped:
        rows.append(
            " & ".join(
                [
                    PROCEDURE_NAMES.get(proc, tex_escape(proc)),
                    MODEL_NAMES.get(model, tex_escape(model)),
                    CONTROL_NAMES.get(control, tex_escape(control)),
                    str(len(g)),
                    f"{fmt(g.identity_cosine.median())} {{\\scriptsize({fmt(g.identity_cosine.min())}--{fmt(g.identity_cosine.max())})}}",
                    fmt(g.change_localization.median()),
                    fmt(g.change_target.median(), 1),
                    fmt(g.latency_s.median(), 0),
                    fmt(g.cost_estimate_usd.median(), 3),
                ]
            )
            + r" \\"
        )
    body = "\n".join(rows)
    tex = (
        "% Generated by scripts/aggregate.py - do not edit by hand.\n"
        r"\begin{tabular}{lllrlllrr}" "\n"
        r"\toprule" "\n"
        r"Procedure & Model & Control & $n$ & Identity$\uparrow$ & Loc.$\uparrow$ & $\Delta E_{\mathrm{tgt}}$ & Lat.\,(s) & Cost\,(\$) \\" "\n"
        r"\midrule" "\n"
        f"{body}\n"
        r"\bottomrule" "\n"
        r"\end{tabular}" "\n"
    )
    (TABLES_DIR / "main_results.tex").write_text(tex, encoding="utf-8")


def write_setup_models() -> None:
    rows = []
    for yml in sorted(MODEL_CONFIGS_DIR.glob("*.yaml")):
        cfg = yaml.safe_load(yml.read_text(encoding="utf-8"))
        if cfg.get("type") != "fal":
            continue  # local/open-weight configs exist in the repo but weren't benchmarked
        name = MODEL_NAMES.get(cfg["name"], tex_escape(cfg["name"]))
        endpoint = tex_escape(cfg.get("model", ""))
        cost = cfg.get("cost_per_image_usd")
        cost_s = f"{cost:.3f}" if isinstance(cost, (int, float)) else "--"
        rows.append(f"{name} & {{\\scriptsize\\texttt{{{endpoint}}}}} & {cost_s} \\\\")
    tex = (
        "% Generated by scripts/aggregate.py - do not edit by hand.\n"
        r"\begin{tabular}{llr}" "\n"
        r"\toprule" "\n"
        r"Model & Endpoint & Cost/image (\$) \\" "\n"
        r"\midrule" "\n" + "\n".join(rows) + "\n"
        r"\bottomrule" "\n"
        r"\end{tabular}" "\n"
    )
    (TABLES_DIR / "setup_models.tex").write_text(tex, encoding="utf-8")


def write_numbers(df: pd.DataFrame, n_runs_total: int, n_runs_scored: int) -> None:
    chained = df[df.procedure.str.contains("_then_")]
    single = df[~df.procedure.str.contains("_then_")]
    comp = single[single.control == "masked_composite"]
    prom = single[single.control == "prompt_only"]
    inp = single[single.control == "masked_inpaint"]
    gt = df.gt_identity_cosine.dropna()

    def m(name, value):
        return f"\\newcommand{{\\{name}}}{{{value}}}\n"

    out = "% Generated by scripts/aggregate.py - do not edit by hand.\n"
    out += m("NumScoredEdits", len(df))
    out += m("NumRunsTotal", n_runs_total)
    out += m("NumRunsScored", n_runs_scored)
    out += m("NumModelsScored", df.model.nunique())
    out += m("NumFacesScored", df.face_id.nunique())
    out += m("MedLocComposite", fmt(comp.change_localization.median()))
    out += m("LocCompositeMin", fmt(comp.change_localization.min()))
    out += m("LocCompositeMax", fmt(comp.change_localization.max()))
    out += m("MedLocPromptOnly", fmt(prom.change_localization.median()))
    out += m("LocPromptOnlyMin", fmt(prom.change_localization.min()))
    out += m("LocPromptOnlyMax", fmt(prom.change_localization.max()))
    out += m("MedIdentityComposite", fmt(comp.identity_cosine.median()))
    out += m("MedIdentityPromptOnly", fmt(prom.identity_cosine.median()))
    out += m("IdentityMinAll", fmt(df.identity_cosine.min()))
    out += m("IdentityMaxAll", fmt(df.identity_cosine.max()))
    below = df[df.identity_cosine < 0.6]
    out += m("NumBelowFloor", len(below))
    out += m("NumBelowFloorFlux", len(below[below.model == "flux_2_pro"]))
    flux_po = df[(df.model == "flux_2_pro") & (df.control == "prompt_only")]
    out += m("MedIdentityFluxPromptOnly", fmt(flux_po.identity_cosine.median()))
    out += m("MedTgtFluxPromptOnly", fmt(flux_po.change_target.median(), 1))
    nb = df[df.model.isin(["nano_banana_pro", "nano_banana_2"])]
    out += m("MedIdentityNanoBanana", fmt(nb.identity_cosine.median()))
    out += m("MedTgtNanoBanana", fmt(nb.change_target.median(), 1))
    out += m("MedLocInpaint", fmt(inp.change_localization.median()))
    out += m("LocInpaintMin", fmt(inp.change_localization.min()))
    out += m("LocInpaintMax", fmt(inp.change_localization.max()))
    out += m("MedIdentityInpaint", fmt(inp.identity_cosine.median()))
    out += m("MedTgtComposite", fmt(comp.change_target.median(), 1))
    out += m("MedOffComposite", fmt(comp.change_offtarget.median(), 2))
    out += m("MedTgtPromptOnly", fmt(prom.change_target.median(), 1))
    out += m("MedOffPromptOnly", fmt(prom.change_offtarget.median(), 2))
    out += m("MedTgtInpaint", fmt(inp.change_target.median(), 1))
    out += m("MedOffInpaint", fmt(inp.change_offtarget.median(), 2))
    inp_f = inp[inp.procedure == "deep_plane_facelift"]
    inp_r = inp[inp.procedure == "rhinoplasty"]
    out += m("InpaintFaceliftLoc", fmt(inp_f.change_localization.median()))
    out += m("InpaintFaceliftIdentity", fmt(inp_f.identity_cosine.median()))
    out += m("InpaintFaceliftTgt", fmt(inp_f.change_target.median(), 1))
    out += m("InpaintRhinoLoc", fmt(inp_r.change_localization.median()))
    out += m("InpaintRhinoIdentity", fmt(inp_r.identity_cosine.median()))
    out += m("InpaintRhinoTgt", fmt(inp_r.change_target.median(), 1))
    out += m("InpaintRhinoOff", fmt(inp_r.change_offtarget.median(), 1))
    out += m("NumChained", len(chained))
    out += m("ChainedIdentityLow", fmt(chained.identity_cosine.min()))
    out += m("ChainedIdentityHigh", fmt(chained.identity_cosine.max()))
    out += m("ChainedLocLow", fmt(chained.change_localization.min()))
    out += m("ChainedLocHigh", fmt(chained.change_localization.max()))
    out += m("MedGtCosine", fmt(gt.median()))
    out += m("GtCosineMin", fmt(gt.min()))
    out += m("GtCosineMax", fmt(gt.max()))
    out += m("MedGtCosineFacelift", fmt(df[df.procedure == "deep_plane_facelift"].gt_identity_cosine.dropna().median()))
    out += m("MedGtCosineRhino", fmt(df[df.procedure == "rhinoplasty"].gt_identity_cosine.dropna().median()))
    out += m("MedLatency", fmt(df.latency_s.median(), 0))
    out += m("MedCost", fmt(df.cost_estimate_usd.median(), 3))
    (TABLES_DIR / "numbers.tex").write_text(out, encoding="utf-8")


def main() -> None:
    raw = load_runs()
    n_runs_total = raw.run_id.nunique()
    df = normalize(raw)
    df = df[(df.ok == True) & df.identity_cosine.notna()]  # noqa: E712
    n_runs_scored = df.run_id.nunique()
    df = dedupe(df)

    keep = [
        "run_id", "stem", "face_id", "model", "procedure", "control",
        *METRIC_COLS, "latency_s", "cost_estimate_usd", "cached", "legacy_regions",
    ]
    DATA_DIR.mkdir(exist_ok=True)
    df[keep].to_csv(DATA_DIR / "canonical_rows.csv", index=False)

    write_main_results(df)
    write_setup_models()
    write_numbers(df, n_runs_total, n_runs_scored)

    print(f"runs total={n_runs_total} scored={n_runs_scored} canonical rows={len(df)}")
    print(df.groupby(["procedure", "model", "control"]).size().to_string())


if __name__ == "__main__":
    main()
